/*!	\file /home/hust/CUDA-Z-add-int8/src/build.h
	\brief SVN revision definition.
	\warning This file is automatically generated by script make_build_svn.pl.
	\author Andriy Golovnya <andriy.golovnya@gmail.com> http://redscorp.net/
	\url http://cuda-z.sf.net/ http://sf.net/projects/cuda-z/
	\license GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
*/

#ifndef CZ_BUILD_H
#define CZ_BUILD_H

#define CZ_VER_BUILD			/*!< SVN revision numeric constant. */
#define CZ_VER_BUILD_STRING	""	/*!< SVN revision string constant. */
#define CZ_VER_BUILD_URL	"Unknown"	/*!< SVN repository URL. */

#endif /*CZ_BUILD_H*/
